### ISSUE TITLE
How do I get random numbers on L4RE

### ISSUE THREAD

**Issue by josephlr** [kernkonzept/l4re-core#1]
I'm working on the [`getrandom` Rust crate](https://github.com/rust-random/getrandom), and we're looking to add an implementation for the new [`x86_64-unknown-l4re-uclibc`](https://github.com/rust-lang/rust/blob/master/src/librustc_target/spec/x86_64_unknown_l4re_uclibc.rs) target.

Is there an easy way (like Linux's [`getrandom(2)`](http://man7.org/linux/man-pages/man2/getrandom.2.html)) to get entropy on L4Re?

**Comment by lonvia** [comment]
Not really, I'm afraid. The L4Re kernel does not provide randomness by itself. Instead a user-land service would need to provide randomness using appropriate hardware for the system. There is currently no such service implemented as part of the L4Re core services, so you'd have to write your own.

**Comment by josephlr** [comment]
Thanks for the response @lonvia 

We're just going to fallback to using `RDRAND` for crypto RNG then, as it looks like l4re is only on x86_64 at the moment.

**Comment by icedieler** [comment]
> ... l4re is only on x86_64 at the moment.

That is a false impression. L4Re supports x86, ARM and MIPS all in 32 and 64 bit.

**Comment by josephlr** [comment]
> That is a false impression. L4Re supports x86, ARM and MIPS all in 32 and 64 bit.

Sorry, I meant to say that the [only supported Rust targets are for x86_64](https://github.com/rust-lang/rust/blob/b8ec4c4d11ede0fba333a0474ed473dbe82aacf1/src/librustc_target/spec/mod.rs#L414).

**Comment by jermar** [comment]
I guess this can be closed now...
