### ISSUE TITLE
Run L4Re with AGL VM

### ISSUE THREAD

**Issue by skisssbb** [kernkonzept/l4re-core#3]
Dear Kernkonzept Team,

in the course of a research project as part of my master program "Cybersecurity":

"Performance Analysis of different virtualization techniques in automotive environment"

I came across L4Re solution. The research intends to run deploy AGL as VM on different Hypervisor environment and perform benchmarking. However, the only tutorial on how to deploy a VM on L4Re I could find was https://github.com/kernkonzept/manifest/wiki/LinuxVM.

I would like to ask if there is any guide/tutorial on how to deploy arbitary VM image on L4Re (e.g AGL image in .wic or .vmdk etc.), since apparently there was a colaboration between AGL and Kernkonzept before [1].

[1] https://iot.bzh/images/public/2019/AMM_Tokyo_0319/AMM-AGL-virtualization-using-L4Re.pdf

Your help would be much appreciated. Maybe I could contribute to the project with my research. I look forward to your response.

Best regards

**Comment by jermar** [comment]
There is also a more technical presentation from the same event on the same topic:
https://static.sched.com/hosted_files/aglammjapan2019/37/under-the-hood-l4re-agl.pdf

In principle the steps are more or less similar to those in the tutorial, depending on how similar is your goal. For the AGL demo, the configuration was quite involving as we had to partition the SoC between the two VMs and arrange pass-through for them. We had to make changes to the VM device trees and work-around various problems mentioned in the first presentation on pages 24, 25 and 26. OTOH, running just one VM on the system is going to be easier and closer to the tutorials.

**Comment by skisssbb** [comment]
Dear @jermar, thank you for your quick response. However, there are no pages 24, 25, 26 in the PDF.

**Comment by phipse** [comment]
>  We had to make changes to the VM device trees and work-around various problems mentioned in the first presentation on pages 24, 25 and 26.

refers to 

> [1] https://iot.bzh/images/public/2019/AMM_Tokyo_0319/AMM-AGL-virtualization-using-L4Re.pdf

**Comment by skisssbb** [comment]
Dear @phipse and @jermar, 

since the 2 PDFs are not really a walk through tutorial and the tutorial provided by L4Re https://github.com/kernkonzept/manifest/wiki/LinuxVM doesn't really cover the case of running an arbitary (lets say AGL, Debian or ubuntu) on top of L4Re Hypervisor.

My goal is to run 1 VM on top of the L4Re Hypervisor to measure the speed and performance. Could you guys help me with a tutorial/walk-through set up of the system?

I would be very grateful.

Best regards

Quang Anh Dang

**Comment by jermar** [comment]
Running one VM will make things easier. If you don't need HW pass-through (but most likely you do, right?) the LinuxVM turorial should suffice. HW pass-through requires more configuration and is more involving. There is a tutorial for a simple device pass-through scenario:

https://github.com/kernkonzept/manifest/wiki/HwPassThrough

I am afraid no tutorial can be general enough to apply to all your needs. You will need to try to figure things on your own and extrapolate the skills learned from the tutorials to a bigger scenario. Of course, if you have a specific question, please feel free to ask (preferably on l4-hackers@). I am going to close this issue now.
