### ISSUE TITLE
Is there a L4Re GUI library?

### ISSUE THREAD

**Issue by lonnietc** [kernkonzept/l4re-core#5]
Hello,

I have been searching for some L4Re libraries but have not found much additional resources thus far.

Where can I obtain the L4Re libraries, drivers, to build GUI and Sound applications for the hypervisor?

Also, is there a more active support channels somewhere Slack, Discord, etc.?
Thanks

**Comment by alacko** [comment]
Hi, all what's available publicly is here: http://l4re.org/download/snapshots/l4re-snapshot-22.04.0.tar.xz, also containing base graphical libraries.

**Comment by lonnietc** [comment]
@alacko  Is there an documentation on how to compile up something that includes a graphical library. I am interested in seeing something run that has some type of a graphical layer running since my goal will be to (hopefully) port a Linux app (FreeRDP) to run, but that may take some time as well.

I wanted to download, or compile, some type of L4Re ISO that would boot up on a x86_64 platform and run in RAM just to see how it works on real hardware.

Thanks
